// This file is auto-generated by @hey-api/openapi-ts

export const Body_documents_upload_private_documentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_documents-upload_private_document'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BranchCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 128,
            title: 'Slug'
        },
        branch_gstin: {
            type: 'string',
            maxLength: 15,
            title: 'Branch Gstin'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name', 'slug', 'branch_gstin'],
    title: 'BranchCreate'
} as const;

export const BranchGstStateCreateSchema = {
    properties: {
        branch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Branch Id'
        },
        gst_state_code_id: {
            type: 'string',
            format: 'uuid',
            title: 'Gst State Code Id'
        }
    },
    type: 'object',
    required: ['branch_id', 'gst_state_code_id'],
    title: 'BranchGstStateCreate'
} as const;

export const BranchGstStatePublicSchema = {
    properties: {
        branch_id: {
            type: 'string',
            format: 'uuid',
            title: 'Branch Id'
        },
        gst_state_code_id: {
            type: 'string',
            format: 'uuid',
            title: 'Gst State Code Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['branch_id', 'gst_state_code_id', 'id'],
    title: 'BranchGstStatePublic'
} as const;

export const BranchGstStatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BranchGstStatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BranchGstStatesPublic'
} as const;

export const BranchPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 128,
            title: 'Slug'
        },
        branch_gstin: {
            type: 'string',
            maxLength: 15,
            title: 'Branch Gstin'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'branch_gstin', 'id'],
    title: 'BranchPublic'
} as const;

export const BranchUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        branch_gstin: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 15
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch Gstin'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'BranchUpdate'
} as const;

export const BranchesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BranchPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BranchesPublic'
} as const;

export const ClientRateContractCreateSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        product_name: {
            type: 'string',
            maxLength: 255,
            title: 'Product Name'
        },
        sku: {
            type: 'string',
            maxLength: 128,
            title: 'Sku'
        },
        agreed_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Agreed Rate'
        },
        gst_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Gst Rate'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['company_id', 'product_name', 'sku', 'agreed_rate', 'gst_rate'],
    title: 'ClientRateContractCreate'
} as const;

export const ClientRateContractPublicSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        product_name: {
            type: 'string',
            maxLength: 255,
            title: 'Product Name'
        },
        sku: {
            type: 'string',
            maxLength: 128,
            title: 'Sku'
        },
        agreed_rate: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Agreed Rate'
        },
        gst_rate: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Gst Rate'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['company_id', 'product_name', 'sku', 'agreed_rate', 'gst_rate', 'id'],
    title: 'ClientRateContractPublic'
} as const;

export const ClientRateContractUpdateSchema = {
    properties: {
        product_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        agreed_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Agreed Rate'
        },
        gst_rate: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gst Rate'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ClientRateContractUpdate'
} as const;

export const ClientRateContractsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ClientRateContractPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ClientRateContractsPublic'
} as const;

export const CompaniesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CompanyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CompaniesPublic'
} as const;

export const CompanyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        payment_term: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Term'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CompanyCreate'
} as const;

export const CompanyEmailDomainCreateSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        domain_pattern: {
            type: 'string',
            maxLength: 255,
            title: 'Domain Pattern'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['company_id', 'domain_pattern'],
    title: 'CompanyEmailDomainCreate'
} as const;

export const CompanyEmailDomainPublicSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        domain_pattern: {
            type: 'string',
            maxLength: 255,
            title: 'Domain Pattern'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['company_id', 'domain_pattern', 'id'],
    title: 'CompanyEmailDomainPublic'
} as const;

export const CompanyEmailDomainUpdateSchema = {
    properties: {
        domain_pattern: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domain Pattern'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'CompanyEmailDomainUpdate'
} as const;

export const CompanyEmailDomainsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CompanyEmailDomainPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CompanyEmailDomainsPublic'
} as const;

export const CompanyPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        payment_term: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Term'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'CompanyPublic'
} as const;

export const CompanyUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        payment_term: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Term'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'CompanyUpdate'
} as const;

export const CompanyValidationAssignmentCreateSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        validation_rule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Validation Rule Id'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: true
        }
    },
    type: 'object',
    required: ['company_id', 'validation_rule_id'],
    title: 'CompanyValidationAssignmentCreate'
} as const;

export const CompanyValidationAssignmentPublicSchema = {
    properties: {
        company_id: {
            type: 'string',
            format: 'uuid',
            title: 'Company Id'
        },
        validation_rule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Validation Rule Id'
        },
        is_enabled: {
            type: 'boolean',
            title: 'Is Enabled',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['company_id', 'validation_rule_id', 'id'],
    title: 'CompanyValidationAssignmentPublic'
} as const;

export const CompanyValidationAssignmentUpdateSchema = {
    properties: {
        is_enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Enabled'
        }
    },
    type: 'object',
    title: 'CompanyValidationAssignmentUpdate'
} as const;

export const CompanyValidationAssignmentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CompanyValidationAssignmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CompanyValidationAssignmentsPublic'
} as const;

export const DocumentAccessLinkSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'DocumentAccessLink'
} as const;

export const DocumentPublicSchema = {
    properties: {
        file_name: {
            type: 'string',
            maxLength: 255,
            title: 'File Name'
        },
        mime_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mime Type'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        uploaded_by_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaded By User Id'
        },
        size_bytes: {
            type: 'integer',
            title: 'Size Bytes'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['file_name', 'id', 'uploaded_by_user_id', 'size_bytes'],
    title: 'DocumentPublic'
} as const;

export const DocumentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/DocumentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'DocumentsPublic'
} as const;

export const GstStateCodePublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 2,
            title: 'Code'
        },
        description: {
            type: 'string',
            maxLength: 255,
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['code', 'description', 'id'],
    title: 'GstStateCodePublic'
} as const;

export const GstStateCodesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/GstStateCodePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'GstStateCodesPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MailAccessTypeSchema = {
    type: 'string',
    enum: ['OrderUser', 'OrderInternalUser'],
    title: 'MailAccessType'
} as const;

export const MailboxConfigCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        app_password: {
            type: 'string',
            maxLength: 255,
            minLength: 8,
            title: 'App Password'
        }
    },
    type: 'object',
    required: ['email', 'app_password'],
    title: 'MailboxConfigCreate'
} as const;

export const MailboxConfigPublicSchema = {
    properties: {
        scope_type: {
            '$ref': '#/components/schemas/MailboxScopeType'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        imap_host: {
            type: 'string',
            maxLength: 255,
            title: 'Imap Host',
            default: 'imap.mail.yahoo.com'
        },
        imap_port: {
            type: 'integer',
            title: 'Imap Port',
            default: 993
        },
        imap_ssl: {
            type: 'boolean',
            title: 'Imap Ssl',
            default: true
        },
        smtp_host: {
            type: 'string',
            maxLength: 255,
            title: 'Smtp Host',
            default: 'smtp.bizmail.yahoo.com'
        },
        smtp_port: {
            type: 'integer',
            title: 'Smtp Port',
            default: 465
        },
        smtp_ssl: {
            type: 'boolean',
            title: 'Smtp Ssl',
            default: true
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['scope_type', 'email', 'id'],
    title: 'MailboxConfigPublic'
} as const;

export const MailboxConfigUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        app_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'App Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'MailboxConfigUpdate'
} as const;

export const MailboxScopeTypeSchema = {
    type: 'string',
    enum: ['centralOrderMail', 'userLinked'],
    title: 'MailboxScopeType'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        mail_access_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MailAccessType'
                },
                {
                    type: 'null'
                }
            ]
        },
        mail_app_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mail App Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserMailAccessCreateSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        access_type: {
            '$ref': '#/components/schemas/MailAccessType'
        },
        app_password: {
            type: 'string',
            maxLength: 255,
            minLength: 8,
            title: 'App Password'
        }
    },
    type: 'object',
    required: ['user_id', 'access_type', 'app_password'],
    title: 'UserMailAccessCreate'
} as const;

export const UserMailAccessPublicSchema = {
    properties: {
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        mailbox_config_id: {
            type: 'string',
            format: 'uuid',
            title: 'Mailbox Config Id'
        },
        access_type: {
            '$ref': '#/components/schemas/MailAccessType'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['user_id', 'mailbox_config_id', 'access_type', 'id'],
    title: 'UserMailAccessPublic'
} as const;

export const UserMailAccessUpdateSchema = {
    properties: {
        access_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MailAccessType'
                },
                {
                    type: 'null'
                }
            ]
        },
        app_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'App Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'UserMailAccessUpdate'
} as const;

export const UserMailAccessesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserMailAccessPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UserMailAccessesPublic'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        mail_access_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MailAccessType'
                },
                {
                    type: 'null'
                }
            ]
        },
        mail_app_password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mail App Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const ValidationRuleCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 128,
            title: 'Key'
        },
        label: {
            type: 'string',
            maxLength: 255,
            title: 'Label'
        },
        definition_json: {
            type: 'string',
            maxLength: 5000,
            title: 'Definition Json',
            default: '{}'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['key', 'label'],
    title: 'ValidationRuleCreate'
} as const;

export const ValidationRulePublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 128,
            title: 'Key'
        },
        label: {
            type: 'string',
            maxLength: 255,
            title: 'Label'
        },
        definition_json: {
            type: 'string',
            maxLength: 5000,
            title: 'Definition Json',
            default: '{}'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['key', 'label', 'id'],
    title: 'ValidationRulePublic'
} as const;

export const ValidationRuleUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        definition_json: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition Json'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'ValidationRuleUpdate'
} as const;

export const ValidationRulesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ValidationRulePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ValidationRulesPublic'
} as const;