// This file is auto-generated by @hey-api/openapi-ts

export type Body_documents_upload_private_document = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BranchCreate = {
    name: string;
    slug: string;
    branch_gstin: string;
    is_active?: boolean;
};

export type BranchesPublic = {
    data: Array<BranchPublic>;
    count: number;
};

export type BranchGstStateCreate = {
    branch_id: string;
    gst_state_code_id: string;
};

export type BranchGstStatePublic = {
    branch_id: string;
    gst_state_code_id: string;
    id: string;
    created_at?: (string | null);
};

export type BranchGstStatesPublic = {
    data: Array<BranchGstStatePublic>;
    count: number;
};

export type BranchPublic = {
    name: string;
    slug: string;
    branch_gstin: string;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type BranchUpdate = {
    name?: (string | null);
    slug?: (string | null);
    branch_gstin?: (string | null);
    is_active?: (boolean | null);
};

export type ClientRateContractCreate = {
    company_id: string;
    product_name: string;
    sku: string;
    agreed_rate: (number | string);
    gst_rate: (number | string);
    is_active?: boolean;
};

export type ClientRateContractPublic = {
    company_id: string;
    product_name: string;
    sku: string;
    agreed_rate: string;
    gst_rate: string;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ClientRateContractsPublic = {
    data: Array<ClientRateContractPublic>;
    count: number;
};

export type ClientRateContractUpdate = {
    product_name?: (string | null);
    sku?: (string | null);
    agreed_rate?: (number | string | null);
    gst_rate?: (number | string | null);
    is_active?: (boolean | null);
};

export type CompaniesPublic = {
    data: Array<CompanyPublic>;
    count: number;
};

export type CompanyCreate = {
    name: string;
    payment_term?: (string | null);
    is_active?: boolean;
};

export type CompanyEmailDomainCreate = {
    company_id: string;
    domain_pattern: string;
    is_active?: boolean;
};

export type CompanyEmailDomainPublic = {
    company_id: string;
    domain_pattern: string;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type CompanyEmailDomainsPublic = {
    data: Array<CompanyEmailDomainPublic>;
    count: number;
};

export type CompanyEmailDomainUpdate = {
    domain_pattern?: (string | null);
    is_active?: (boolean | null);
};

export type CompanyPublic = {
    name: string;
    payment_term?: (string | null);
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type CompanyUpdate = {
    name?: (string | null);
    payment_term?: (string | null);
    is_active?: (boolean | null);
};

export type CompanyValidationAssignmentCreate = {
    company_id: string;
    validation_rule_id: string;
    is_enabled?: boolean;
};

export type CompanyValidationAssignmentPublic = {
    company_id: string;
    validation_rule_id: string;
    is_enabled?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type CompanyValidationAssignmentsPublic = {
    data: Array<CompanyValidationAssignmentPublic>;
    count: number;
};

export type CompanyValidationAssignmentUpdate = {
    is_enabled?: (boolean | null);
};

export type DocumentAccessLink = {
    url: string;
};

export type DocumentPublic = {
    file_name: string;
    mime_type?: (string | null);
    id: string;
    uploaded_by_user_id: string;
    size_bytes: number;
    created_at?: (string | null);
};

export type DocumentsPublic = {
    data: Array<DocumentPublic>;
    count: number;
};

export type GstStateCodePublic = {
    code: string;
    description: string;
    id: string;
};

export type GstStateCodesPublic = {
    data: Array<GstStateCodePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MailAccessType = 'OrderUser' | 'OrderInternalUser';

export type MailboxConfigCreate = {
    email: string;
    app_password: string;
};

export type MailboxConfigPublic = {
    scope_type: MailboxScopeType;
    email: string;
    imap_host?: string;
    imap_port?: number;
    imap_ssl?: boolean;
    smtp_host?: string;
    smtp_port?: number;
    smtp_ssl?: boolean;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type MailboxConfigUpdate = {
    email?: (string | null);
    app_password?: (string | null);
    is_active?: (boolean | null);
};

export type MailboxScopeType = 'centralOrderMail' | 'userLinked';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
    mail_access_type?: (MailAccessType | null);
    mail_app_password?: (string | null);
};

export type UserMailAccessCreate = {
    user_id: string;
    access_type: MailAccessType;
    app_password: string;
};

export type UserMailAccessesPublic = {
    data: Array<UserMailAccessPublic>;
    count: number;
};

export type UserMailAccessPublic = {
    user_id: string;
    mailbox_config_id: string;
    access_type: MailAccessType;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type UserMailAccessUpdate = {
    access_type?: (MailAccessType | null);
    app_password?: (string | null);
    is_active?: (boolean | null);
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
    mail_access_type?: (MailAccessType | null);
    mail_app_password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ValidationRuleCreate = {
    key: string;
    label: string;
    definition_json?: string;
    is_active?: boolean;
};

export type ValidationRulePublic = {
    key: string;
    label: string;
    definition_json?: string;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ValidationRulesPublic = {
    data: Array<ValidationRulePublic>;
    count: number;
};

export type ValidationRuleUpdate = {
    label?: (string | null);
    definition_json?: (string | null);
    is_active?: (boolean | null);
};

export type BranchesListBranchesData = {
    limit?: number;
    skip?: number;
};

export type BranchesListBranchesResponse = (BranchesPublic);

export type BranchesCreateBranchData = {
    requestBody: BranchCreate;
};

export type BranchesCreateBranchResponse = (BranchPublic);

export type BranchesUpdateBranchData = {
    branchId: string;
    requestBody: BranchUpdate;
};

export type BranchesUpdateBranchResponse = (BranchPublic);

export type BranchesDeleteBranchData = {
    branchId: string;
};

export type BranchesDeleteBranchResponse = (Message);

export type BranchesListGstStatesResponse = (GstStateCodesPublic);

export type BranchesListBranchStatesData = {
    branchId: string;
};

export type BranchesListBranchStatesResponse = (BranchGstStatesPublic);

export type BranchesAttachBranchStateData = {
    branchId: string;
    requestBody: BranchGstStateCreate;
};

export type BranchesAttachBranchStateResponse = (BranchGstStatePublic);

export type BranchesDetachBranchStateData = {
    branchId: string;
    mappingId: string;
};

export type BranchesDetachBranchStateResponse = (Message);

export type CompaniesListCompaniesData = {
    limit?: number;
    skip?: number;
};

export type CompaniesListCompaniesResponse = (CompaniesPublic);

export type CompaniesCreateCompanyData = {
    requestBody: CompanyCreate;
};

export type CompaniesCreateCompanyResponse = (CompanyPublic);

export type CompaniesUpdateCompanyData = {
    companyId: string;
    requestBody: CompanyUpdate;
};

export type CompaniesUpdateCompanyResponse = (CompanyPublic);

export type CompaniesDeleteCompanyData = {
    companyId: string;
};

export type CompaniesDeleteCompanyResponse = (Message);

export type CompaniesListCompanyDomainsData = {
    companyId: string;
};

export type CompaniesListCompanyDomainsResponse = (CompanyEmailDomainsPublic);

export type CompaniesCreateCompanyDomainData = {
    companyId: string;
    requestBody: CompanyEmailDomainCreate;
};

export type CompaniesCreateCompanyDomainResponse = (CompanyEmailDomainPublic);

export type CompaniesUpdateCompanyDomainData = {
    domainId: string;
    requestBody: CompanyEmailDomainUpdate;
};

export type CompaniesUpdateCompanyDomainResponse = (CompanyEmailDomainPublic);

export type CompaniesDeleteCompanyDomainData = {
    domainId: string;
};

export type CompaniesDeleteCompanyDomainResponse = (Message);

export type DocumentsUploadPrivateDocumentData = {
    formData: Body_documents_upload_private_document;
};

export type DocumentsUploadPrivateDocumentResponse = (DocumentPublic);

export type DocumentsListDocumentsData = {
    limit?: number;
    skip?: number;
};

export type DocumentsListDocumentsResponse = (DocumentsPublic);

export type DocumentsGetDocumentData = {
    documentId: string;
};

export type DocumentsGetDocumentResponse = (DocumentPublic);

export type DocumentsDeleteDocumentData = {
    documentId: string;
};

export type DocumentsDeleteDocumentResponse = (Message);

export type DocumentsGetDocumentAccessLinkData = {
    documentId: string;
};

export type DocumentsGetDocumentAccessLinkResponse = (DocumentAccessLink);

export type DocumentsDownloadDocumentData = {
    documentId: string;
};

export type DocumentsDownloadDocumentResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MailAccessGetCentralMailboxResponse = ((MailboxConfigPublic | null));

export type MailAccessUpsertCentralMailboxData = {
    requestBody: MailboxConfigCreate;
};

export type MailAccessUpsertCentralMailboxResponse = (MailboxConfigPublic);

export type MailAccessUpdateCentralMailboxData = {
    requestBody: MailboxConfigUpdate;
};

export type MailAccessUpdateCentralMailboxResponse = (MailboxConfigPublic);

export type MailAccessListUserMailAccessesData = {
    limit?: number;
    skip?: number;
};

export type MailAccessListUserMailAccessesResponse = (UserMailAccessesPublic);

export type MailAccessGrantUserMailAccessData = {
    requestBody: UserMailAccessCreate;
};

export type MailAccessGrantUserMailAccessResponse = (UserMailAccessPublic);

export type MailAccessUpdateUserMailAccessData = {
    requestBody: UserMailAccessUpdate;
    userId: string;
};

export type MailAccessUpdateUserMailAccessResponse = (UserMailAccessPublic);

export type MailAccessRevokeUserMailAccessData = {
    userId: string;
};

export type MailAccessRevokeUserMailAccessResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RateContractsListRateContractsData = {
    companyId?: (string | null);
    limit?: number;
    skip?: number;
};

export type RateContractsListRateContractsResponse = (ClientRateContractsPublic);

export type RateContractsCreateRateContractData = {
    requestBody: ClientRateContractCreate;
};

export type RateContractsCreateRateContractResponse = (ClientRateContractPublic);

export type RateContractsUpdateRateContractData = {
    contractId: string;
    requestBody: ClientRateContractUpdate;
};

export type RateContractsUpdateRateContractResponse = (ClientRateContractPublic);

export type RateContractsDeleteRateContractData = {
    contractId: string;
};

export type RateContractsDeleteRateContractResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type ValidationsListValidationRulesData = {
    limit?: number;
    skip?: number;
};

export type ValidationsListValidationRulesResponse = (ValidationRulesPublic);

export type ValidationsCreateValidationRuleData = {
    requestBody: ValidationRuleCreate;
};

export type ValidationsCreateValidationRuleResponse = (ValidationRulePublic);

export type ValidationsUpdateValidationRuleData = {
    requestBody: ValidationRuleUpdate;
    ruleId: string;
};

export type ValidationsUpdateValidationRuleResponse = (ValidationRulePublic);

export type ValidationsDeleteValidationRuleData = {
    ruleId: string;
};

export type ValidationsDeleteValidationRuleResponse = (Message);

export type ValidationsListAssignmentsData = {
    companyId?: (string | null);
};

export type ValidationsListAssignmentsResponse = (CompanyValidationAssignmentsPublic);

export type ValidationsCreateAssignmentData = {
    requestBody: CompanyValidationAssignmentCreate;
};

export type ValidationsCreateAssignmentResponse = (CompanyValidationAssignmentPublic);

export type ValidationsUpdateAssignmentData = {
    assignmentId: string;
    requestBody: CompanyValidationAssignmentUpdate;
};

export type ValidationsUpdateAssignmentResponse = (CompanyValidationAssignmentPublic);

export type ValidationsDeleteAssignmentData = {
    assignmentId: string;
};

export type ValidationsDeleteAssignmentResponse = (Message);