/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRejectedCentralRouteImport } from './routes/_layout/rejected-central'
import { Route as LayoutMailboxNotProcessedRouteImport } from './routes/_layout/mailbox-not-processed'
import { Route as LayoutMailboxMessageIdsRouteImport } from './routes/_layout/mailbox-message-ids'
import { Route as LayoutMailboxRouteImport } from './routes/_layout/mailbox'
import { Route as LayoutMailAccessRouteImport } from './routes/_layout/mail-access'
import { Route as LayoutCompanyValidationsRouteImport } from './routes/_layout/company-validations'
import { Route as LayoutCompaniesRouteImport } from './routes/_layout/companies'
import { Route as LayoutClientsRouteImport } from './routes/_layout/clients'
import { Route as LayoutBranchesRouteImport } from './routes/_layout/branches'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutCompaniesCompanyIdRouteImport } from './routes/_layout/companies.$companyId'
import { Route as LayoutBranchesCreateBranchRouteImport } from './routes/_layout/branches.createBranch'
import { Route as LayoutBranchesBranchIdRouteImport } from './routes/_layout/branches.$branchId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRejectedCentralRoute = LayoutRejectedCentralRouteImport.update({
  id: '/rejected-central',
  path: '/rejected-central',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMailboxNotProcessedRoute =
  LayoutMailboxNotProcessedRouteImport.update({
    id: '/mailbox-not-processed',
    path: '/mailbox-not-processed',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMailboxMessageIdsRoute = LayoutMailboxMessageIdsRouteImport.update({
  id: '/mailbox-message-ids',
  path: '/mailbox-message-ids',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMailboxRoute = LayoutMailboxRouteImport.update({
  id: '/mailbox',
  path: '/mailbox',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMailAccessRoute = LayoutMailAccessRouteImport.update({
  id: '/mail-access',
  path: '/mail-access',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompanyValidationsRoute =
  LayoutCompanyValidationsRouteImport.update({
    id: '/company-validations',
    path: '/company-validations',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutCompaniesRoute = LayoutCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutClientsRoute = LayoutClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBranchesRoute = LayoutBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCompaniesCompanyIdRoute =
  LayoutCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => LayoutCompaniesRoute,
  } as any)
const LayoutBranchesCreateBranchRoute =
  LayoutBranchesCreateBranchRouteImport.update({
    id: '/createBranch',
    path: '/createBranch',
    getParentRoute: () => LayoutBranchesRoute,
  } as any)
const LayoutBranchesBranchIdRoute = LayoutBranchesBranchIdRouteImport.update({
  id: '/$branchId',
  path: '/$branchId',
  getParentRoute: () => LayoutBranchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/branches': typeof LayoutBranchesRouteWithChildren
  '/clients': typeof LayoutClientsRoute
  '/companies': typeof LayoutCompaniesRouteWithChildren
  '/company-validations': typeof LayoutCompanyValidationsRoute
  '/mail-access': typeof LayoutMailAccessRoute
  '/mailbox': typeof LayoutMailboxRoute
  '/mailbox-message-ids': typeof LayoutMailboxMessageIdsRoute
  '/mailbox-not-processed': typeof LayoutMailboxNotProcessedRoute
  '/rejected-central': typeof LayoutRejectedCentralRoute
  '/settings': typeof LayoutSettingsRoute
  '/branches/$branchId': typeof LayoutBranchesBranchIdRoute
  '/branches/createBranch': typeof LayoutBranchesCreateBranchRoute
  '/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/branches': typeof LayoutBranchesRouteWithChildren
  '/clients': typeof LayoutClientsRoute
  '/companies': typeof LayoutCompaniesRouteWithChildren
  '/company-validations': typeof LayoutCompanyValidationsRoute
  '/mail-access': typeof LayoutMailAccessRoute
  '/mailbox': typeof LayoutMailboxRoute
  '/mailbox-message-ids': typeof LayoutMailboxMessageIdsRoute
  '/mailbox-not-processed': typeof LayoutMailboxNotProcessedRoute
  '/rejected-central': typeof LayoutRejectedCentralRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/branches/$branchId': typeof LayoutBranchesBranchIdRoute
  '/branches/createBranch': typeof LayoutBranchesCreateBranchRoute
  '/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/branches': typeof LayoutBranchesRouteWithChildren
  '/_layout/clients': typeof LayoutClientsRoute
  '/_layout/companies': typeof LayoutCompaniesRouteWithChildren
  '/_layout/company-validations': typeof LayoutCompanyValidationsRoute
  '/_layout/mail-access': typeof LayoutMailAccessRoute
  '/_layout/mailbox': typeof LayoutMailboxRoute
  '/_layout/mailbox-message-ids': typeof LayoutMailboxMessageIdsRoute
  '/_layout/mailbox-not-processed': typeof LayoutMailboxNotProcessedRoute
  '/_layout/rejected-central': typeof LayoutRejectedCentralRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/branches/$branchId': typeof LayoutBranchesBranchIdRoute
  '/_layout/branches/createBranch': typeof LayoutBranchesCreateBranchRoute
  '/_layout/companies/$companyId': typeof LayoutCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/branches'
    | '/clients'
    | '/companies'
    | '/company-validations'
    | '/mail-access'
    | '/mailbox'
    | '/mailbox-message-ids'
    | '/mailbox-not-processed'
    | '/rejected-central'
    | '/settings'
    | '/branches/$branchId'
    | '/branches/createBranch'
    | '/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/branches'
    | '/clients'
    | '/companies'
    | '/company-validations'
    | '/mail-access'
    | '/mailbox'
    | '/mailbox-message-ids'
    | '/mailbox-not-processed'
    | '/rejected-central'
    | '/settings'
    | '/'
    | '/branches/$branchId'
    | '/branches/createBranch'
    | '/companies/$companyId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/branches'
    | '/_layout/clients'
    | '/_layout/companies'
    | '/_layout/company-validations'
    | '/_layout/mail-access'
    | '/_layout/mailbox'
    | '/_layout/mailbox-message-ids'
    | '/_layout/mailbox-not-processed'
    | '/_layout/rejected-central'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/branches/$branchId'
    | '/_layout/branches/createBranch'
    | '/_layout/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rejected-central': {
      id: '/_layout/rejected-central'
      path: '/rejected-central'
      fullPath: '/rejected-central'
      preLoaderRoute: typeof LayoutRejectedCentralRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mailbox-not-processed': {
      id: '/_layout/mailbox-not-processed'
      path: '/mailbox-not-processed'
      fullPath: '/mailbox-not-processed'
      preLoaderRoute: typeof LayoutMailboxNotProcessedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mailbox-message-ids': {
      id: '/_layout/mailbox-message-ids'
      path: '/mailbox-message-ids'
      fullPath: '/mailbox-message-ids'
      preLoaderRoute: typeof LayoutMailboxMessageIdsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mailbox': {
      id: '/_layout/mailbox'
      path: '/mailbox'
      fullPath: '/mailbox'
      preLoaderRoute: typeof LayoutMailboxRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mail-access': {
      id: '/_layout/mail-access'
      path: '/mail-access'
      fullPath: '/mail-access'
      preLoaderRoute: typeof LayoutMailAccessRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/company-validations': {
      id: '/_layout/company-validations'
      path: '/company-validations'
      fullPath: '/company-validations'
      preLoaderRoute: typeof LayoutCompanyValidationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companies': {
      id: '/_layout/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof LayoutCompaniesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/clients': {
      id: '/_layout/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof LayoutClientsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/branches': {
      id: '/_layout/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof LayoutBranchesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/companies/$companyId': {
      id: '/_layout/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof LayoutCompaniesCompanyIdRouteImport
      parentRoute: typeof LayoutCompaniesRoute
    }
    '/_layout/branches/createBranch': {
      id: '/_layout/branches/createBranch'
      path: '/createBranch'
      fullPath: '/branches/createBranch'
      preLoaderRoute: typeof LayoutBranchesCreateBranchRouteImport
      parentRoute: typeof LayoutBranchesRoute
    }
    '/_layout/branches/$branchId': {
      id: '/_layout/branches/$branchId'
      path: '/$branchId'
      fullPath: '/branches/$branchId'
      preLoaderRoute: typeof LayoutBranchesBranchIdRouteImport
      parentRoute: typeof LayoutBranchesRoute
    }
  }
}

interface LayoutBranchesRouteChildren {
  LayoutBranchesBranchIdRoute: typeof LayoutBranchesBranchIdRoute
  LayoutBranchesCreateBranchRoute: typeof LayoutBranchesCreateBranchRoute
}

const LayoutBranchesRouteChildren: LayoutBranchesRouteChildren = {
  LayoutBranchesBranchIdRoute: LayoutBranchesBranchIdRoute,
  LayoutBranchesCreateBranchRoute: LayoutBranchesCreateBranchRoute,
}

const LayoutBranchesRouteWithChildren = LayoutBranchesRoute._addFileChildren(
  LayoutBranchesRouteChildren,
)

interface LayoutCompaniesRouteChildren {
  LayoutCompaniesCompanyIdRoute: typeof LayoutCompaniesCompanyIdRoute
}

const LayoutCompaniesRouteChildren: LayoutCompaniesRouteChildren = {
  LayoutCompaniesCompanyIdRoute: LayoutCompaniesCompanyIdRoute,
}

const LayoutCompaniesRouteWithChildren = LayoutCompaniesRoute._addFileChildren(
  LayoutCompaniesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBranchesRoute: typeof LayoutBranchesRouteWithChildren
  LayoutClientsRoute: typeof LayoutClientsRoute
  LayoutCompaniesRoute: typeof LayoutCompaniesRouteWithChildren
  LayoutCompanyValidationsRoute: typeof LayoutCompanyValidationsRoute
  LayoutMailAccessRoute: typeof LayoutMailAccessRoute
  LayoutMailboxRoute: typeof LayoutMailboxRoute
  LayoutMailboxMessageIdsRoute: typeof LayoutMailboxMessageIdsRoute
  LayoutMailboxNotProcessedRoute: typeof LayoutMailboxNotProcessedRoute
  LayoutRejectedCentralRoute: typeof LayoutRejectedCentralRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBranchesRoute: LayoutBranchesRouteWithChildren,
  LayoutClientsRoute: LayoutClientsRoute,
  LayoutCompaniesRoute: LayoutCompaniesRouteWithChildren,
  LayoutCompanyValidationsRoute: LayoutCompanyValidationsRoute,
  LayoutMailAccessRoute: LayoutMailAccessRoute,
  LayoutMailboxRoute: LayoutMailboxRoute,
  LayoutMailboxMessageIdsRoute: LayoutMailboxMessageIdsRoute,
  LayoutMailboxNotProcessedRoute: LayoutMailboxNotProcessedRoute,
  LayoutRejectedCentralRoute: LayoutRejectedCentralRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
